version: '3'

services:

  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - 5000:5000
    environment:
      - DEBUG=${DEBUG}
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
    volumes:
      - ./app/:/usr/app/
    depends_on:
      postgres:
        # waiting for the database to be ready
        condition: service_healthy

  postgres:
    image: "postgres" # use latest official postgres version
    container_name: postgres-db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database-data:/var/lib/postgresql/data/
    healthcheck:
      # used in flask container depends_on condition to wait for the DB to be ready
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 20s
      retries: 5

volumes:
  database-data:
